# Generated by Django 5.2.17 on 2026-09-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=40, null=True)),
                ('instructor', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('horas', models.PositiveIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Inscrito', 'Inscrito'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Faltó', 'Faltó')], default='Inscrito', max_length=12)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('asistencia', models.FloatField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.curso')),
            ],
            options={
                'ordering': ['curso__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='certificados/')),
                ('curso_detectado', models.CharField(blank=True, max_length=200, null=True)),
                ('participante_detectado', models.CharField(blank=True, max_length=240, null=True)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.inscripcion')),
            ],
            options={
                'ordering': ['-cargado_en'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='DNI/Cédula')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
                'indexes': [models.Index(fields=['apellidos', 'nombres'], name='core_partic_apellid_be4879_idx')],
            },
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.participante'),
        ),
        migrations.AddField(
            model_name='curso',
            name='participantes',
            field=models.ManyToManyField(related_name='cursos', through='core.Inscripcion', to='core.participante'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('participante', 'curso')},
        ),
    ]
